name: Bug Report
description: Report a bug or unexpected behavior in this project.
title: "[Bug] YOUR BUG TITLE HERE"
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide as much detail as possible to help us reproduce and fix the issue.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      placeholder: App crashes when clicking the save button
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Go to the settings page
        2. Click on 'Save'
        3. Observe the error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The settings should be saved without errors.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The app crashes and shows an error message.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment.
      placeholder: |
        - OS: macOS Ventura 13.0
        - Browser: Chrome 110
        - Node.js: 18.0.0
        - App version: 1.2.3
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or error logs here.
      placeholder: Any other information that might be useful.
    validations:
      required: false
