name: Feature Request
description: Suggest a new feature or enhancement for this project.
title: "[Feature Request] YOUR FEATURE TITLE HERE"
labels: ["feature request", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature. Please provide as much detail as possible to help us understand your idea.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: Add support for dark mode
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it important?
      placeholder: Describe the problem or need that this feature addresses.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature in detail.
      placeholder: Explain how you would like this feature to work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: List any alternatives you've thought of.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Any other information that might be useful.
    validations:
      required: false
